#%RAML 0.8
---
baseUri: http://mocksvc.mulesoft.com/mocks/ae299803-02fa-415c-bb8a-4b92566fdde8/mocks/39d9aa85-9a02-46f0-a97f-8c8000e3cbe1
title: UCOP Campus API
version: v1

/Eligibility:
  /IF-eligibility-1:
    /{Home_Campus_Student_Identifier}:
       get:
        responses:
          200:
            body:
              application/json:
                schema: |
                  { "$schema": "http://json-schema.org/schema",
                    "type": "object",
                    "description": "Basic Eligibility",
                    "properties": {
                      "Basic_Eligibility": { "type": "boolean" },
                      "Eligibility_Check_Results": {
                        "type": "array",
                        "minItems": 1,
                        "items": {
                          "type": "object",
                          "properties": {
                            "Check": { "type": "string" },
                            "Result": { "type": "boolean" }
                          },
                          "required": [ "Check", "Result" ]
                        }
                      }
                    },
                    "required": [ "Basic_Eligibility", "Eligibility_Check_Results" ]
                  }
                example: |
                  {
                    "Basic_Eligibility": false,
                    "Eligibility_Check_Results": [
                      {
                        "Check": "Completed Min Units",
                        "Result": false
                      },
                      {
                        "Check": "Good Academic Standing",
                        "Result": true
                      },
                      {
                        "Check": "Full Time Student",
                        "Result": true
                      }
                    ]
                  }

/Calendar:
  /IF-calendar-1:
    /{year}:
        /{term}:
          get:
            responses:
              200:
                body:
                  application/json:
                    schema: |
                      {
                        "$schema": "http://json-schema.org/schema",
                        "type": "object",
                        "properties": {
                          "Events": {
                            "type": "array",
                            "items": {
                              "type": "object",
                              "properties": {
                                "Event": { "type": "string" },
                                "Date": { "type": "string" }
                              },
                              "required": [ "Event", "Date" ]
                            }
                          }
                        },
                        "required": [
                          "Events"
                        ]
                      }
                    example: |
                      {
                        "Events": [
                          {
                          "Event": "Registration_Open_Period",
                          "Date": "value"
                          },
                          {
                          "Event": "Quarter_Begins",
                          "Date": "value"
                          },
                          {
                          "Event": "Quarter_Ends",
                          "Date": "value"
                          },
                          {
                          "Event": "Semester_Begins",
                          "Date": "value"
                          },
                          {
                          "Event": "Semester_Ends",
                          "Date": "value"
                          },
                          {
                          "Event": "Instruction_Starts",
                          "Date": "value"
                          },
                          {
                          "Event": "Instruction_Ends",
                          "Date": "value"
                          },
                          {
                          "Event": "Grade_Submission_Deadline",
                          "Date": "value"
                          },
                          {
                          "Event": "Last_Drop_Day",
                          "Date": "value"
                          },
                          {
                          "Event": "Last_Add_Day",
                          "Date": "value"
                          },
                          {
                          "Event": "Last_Day_Change_Grading_Preference",
                          "Date": "value"
                          }
                        ]
                      }
/courseCatalog:
  /IF-course-1:
    /{year}:
      /{term}:
        get:
          queryParameters:
            hostRequestId:
              description: unique identifier for the course request
          responses:
            200:
              body:
                application/json:
                  schema: |
                    {
                      "$schema": "http://json-schema.org/schema",
                      "type": "object",
                      "properties": {
                        "Requestor": {
                          "type": "string"
                        },
                        "Request_Timestamp": {
                          "type": "string"
                        },
                        "Catalog": {
                          "type": "object",
                          "properties": {
                            "Academic_Term": {
                              "type": "string"
                            },
                            "Academic_Year": {
                              "type": "string"
                            },
                            "Courses_Data": {
                              "type": "array",
                              "items": {
                                "type": "object",
                                "properties": {
                                  "Course Offering Code": {
                                    "type": "string"
                                  },
                                  "Course_Title": {
                                    "type": "string"
                                  },
                                  "Course_Description": {
                                    "type": "string"
                                  },
                                  "Course_Subject": {
                                    "type": "string"
                                  },
                                  "Course Exam Date": {
                                    "type": "string"
                                  },
                                  "Instructors": {
                                    "type": "array",
                                    "items": {
                                      "type": "object",
                                      "properties": {
                                        "Person_Identifier": {
                                          "type": "string"
                                        },
                                        "FirstName": {
                                          "type": "string"
                                        },
                                        "LastName": {
                                          "type": "string"
                                        },
                                        "IsPrimary": {
                                          "type": "boolean"
                                        }
                                      }
                                    }
                                  },
                                  "Units": {
                                    "type": "integer"
                                  },
                                  "Prerequisites": {
                                    "type": "string"
                                  },
                                  "Sections_Data": {
                                    "type": "array",
                                    "items": {
                                      "type": "object",
                                      "properties": {
                                        "Section Offering Code": {
                                          "type": "string"
                                        },
                                        "Section_Resource_Number": {
                                          "type": "string"
                                        },
                                        "Section_Type": {
                                          "type": "string"
                                        },
                                        "Meetings": {
                                          "type": "array",
                                          "items": {
                                            "type": "object",
                                            "properties": {
                                              "Day_of_Week": {
                                                "type": "string"
                                              },
                                              "From_Time": {
                                                "type": "string"
                                              },
                                              "To_Time": {
                                                "type": "string"
                                              }
                                            }
                                          }
                                        },
                                        "Section_Exam_Date": {
                                          "type": "string"
                                        },
                                        "Max_Enrollment_Cap": {
                                          "type": "integer"
                                        },
                                        "Units": {
                                          "type": "string"
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      },
                      "required": [
                        "Requestor",
                        "Request_Timestamp",
                        "Catalog"
                      ]
                    }
                  example: |
                    {
                      "Requestor": "HUB",
                      "Request_Timestamp": "2015-04-21T18:25:43-05:00",
                      "Catalog": {
                          "Academic_Term": "",
                          "Academic_Year": "",
                          "Courses_Data": [
                              {
                                  "Course Offering Code": "value",
                                  "Course_Title": "value",
                                  "Course_Description": "value",
                                  "Course_Subject": "subject 1, subject 2, subject3",
                                  "Course Exam Date": "2015-06-21",
                                  "Instructors": [
                                      {
                                          "Person_Identifier": "12345",
                                          "FirstName": "Joe",
                                          "LastName": "Jackson",
                                          "IsPrimary": true
                                      },
                                      {
                                          "Person_Identifier": "12346",
                                          "FirstName": "Jane",
                                          "LastName": "Darrel",
                                          "IsPrimary": false
                                      }
                                  ],
                                  "Units": 4,
                                  "Prerequisites": "big-text-string",
                                  "Sections_Data": [
                                      {
                                          "Section Offering Code": "value1",
                                          "Section_Resource_Number": "value11",
                                          "Section_Type": "",
                                          "Meetings": [
                                              {
                                                  "Day_of_Week": "Mon",
                                                  "From_Time": "",
                                                  "To_Time": ""
                                              },
                                              {
                                                  "Day_of_Week": "Tue",
                                                  "From_Time": "",
                                                  "To_Time": ""
                                              }
                                          ],
                                          "Section_Exam_Date": "2015-06-28",
                                          "Max_Enrollment_Cap": 50,
                                          "Units": "4"
                                      }
                                  ]
                              }
                          ]
                       }
                    }

/enrollment:
  /IF-enroll-2:
    post:
      body:
        application/json:
          schema: |
            {
              "$schema": "http://json-schema.org/schema",
              "type": "object",
              "properties": {
                "Sender": {
                  "type": "string"
                },
                "Sender_Request_Id": {
                  "type": "string"
                },
                "Host_Campus_Code": {
                  "type": "string"
                },
                "Academic_Term_Type": {
                  "type": "string"
                },
                "Academic_Term": {
                  "type": "string"
                },
                "Academic_Year": {
                  "type": "string"
                },
                "Enrollment_Status": {
                  "type": "string"
                },
                "Section_Resource_Number": {
                  "type": "string"
                },
                "Lecture_Resource_Number": {
                  "type": "string"
                },
                "Course_Title": {
                  "type": "string"
                },
                "Course_Offering_Code": {
                  "type": "string"
                },
                "User_Type": {
                  "type": "string"
                },
                "Home_Campus_User_Identifier": {
                  "type": "string"
                },
                "Home_Campus_User_Eppn": {
                  "type": "string"
                },
                "Host_Campus_User_Identifier": {
                  "type": "string"
                },
                "Host_Campus_User_Eppn": {
                  "type": "string"
                },
                "Last_Name": {
                  "type": "string"
                },
                "First_Name": {
                  "type": "string"
                },
                "Home_Campus_Email": {
                  "type": "string"
                },
                "Host_Campus_Email": {
                  "type": "string"
                }
              },
              "required": [
                "Sender",
                "Sender_Request_Id",
                "Host_Campus_Code",
                "Academic_Term_Type",
                "Academic_Term",
                "Academic_Year",
                "Enrollment_Status",
                "Section_Resource_Number",
                "Lecture_Resource_Number",
                "Course_Title",
                "Course_Offering_Code",
                "User_Type",
                "Home_Campus_User_Identifier",
                "Home_Campus_User_Eppn",
                "Last_Name",
                "First_Name",
                "Home_Campus_Email",
                "Host_Campus_Email"
              ]
            }
          example: |
            {
              "Sender": "CCES-HUB",
              "Sender_Request_Id": "987654321",
              "Host_Campus_Code": "UCSC",
              "Academic_Term_Type": "",
              "Academic_Term": "",
              "Academic_Year": "",
              "Enrollment_Status": "E",
              "Section_Resource_Number": "",
              "Lecture_Resource_Number": "",
              "Course_Title": "",
              "Course_Offering_Code": "",
              "User_Type": "",
              "Home_Campus_User_Identifier": "123456789",
              "Home_Campus_User_Eppn": "jcarberr@brown.edu",
              "Host_Campus_User_Identifier": "",
              "Host_Campus_User_Eppn": "",
              "Last_Name": "",
              "First_Name": "",
              "Home_Campus_Email": "",
              "Host_Campus_Email": ""
            }
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "$schema": "http://json-schema.org/schema",
                  "type": "object",
                  "properties": {
                    "functionality": {
                      "type": "string"
                    },
                    "method": {
                      "type": "string"
                    },
                    "verb": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string"
                    },
                    "confirmationId": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "functionality",
                    "method",
                    "verb",
                    "status",
                    "confirmationId"
                  ]
                }
              example: |
                {
                  "functionality": "Enrollment and Drops",
                  "method": "Enrollment Notification",
                  "verb": "POST",
                  "status": "ACK",
                  "confirmationId": "UCD-123ZULU321"
                }
/PersonallyIdentifiableInformation:
  /IF-PII-1:
    description: Get-Student-PII
    post:
      description: Hub requests PII information from Home and/or Host campus.
      body:
        application/json:
          schema: |
            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "id": "/",
              "type": "object",
              "properties": {
                "Home_Campus_Code": {
                  "id": "Home_Campus_Code",
                  "type": "string"
                },
                "Home_Campus_Email": {
                  "id": "Home_Campus_Email",
                  "type": "string"
                },
                "Home_Campus_User_Eppn": {
                  "id": "Home_Campus_User_Eppn",
                  "type": "string"
                },
                "Home_Campus_User_Identifier": {
                  "id": "Home_Campus_User_Identifier",
                  "type": "string"
                },
                "Timestamp": {
                  "id": "Timestamp",
                  "type": "string"
                },
                "Host_Campus_Code": {
                  "id": "Host_Campus_Code",
                  "type": "string"
                },
                "Host_Campus_Email": {
                  "id": "Host_Campus_Email",
                  "type": "string"
                },
                "Host_Campus_User_Eppn": {
                  "id": "Host_Campus_User_Eppn",
                  "type": "string"
                },
                "Host_Campus_User_Identifier": {
                  "id": "Host_Campus_User_Identifier",
                  "type": "string"
                }
              }
            }
          example: |
            {
               "Home_Campus_Code":"UCB",
               "Home_Campus_Email":"ucb-info@ucop.edu",
               "Home_Campus_User_Eppn":"value",
               "Home_Campus_User_Identifier":"value",
               "Timestamp":"2015-04-23T18:25:43.511Z"
            }
      responses:
        200:
          body:
            application/json: 
              schema: |
                {
                  "$schema": "http://json-schema.org/schema",
                  "type": "object",
                  "properties": {
                    "Student_PII": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "Address": {
                            "type": "string"
                          },
                          "Birthdate": {
                            "type": "string"
                          },
                          "City": {
                            "type": "string"
                          },
                          "Classification": {
                            "type": "string"
                          },
                          "First_Name": {
                            "type": "string"
                          },
                          "Gender": {
                            "type": "string"
                          },
                          "encrypted_SSN": {
                            "type": "string"
                          },
                          "Home_Campus_Code": {
                            "type": "string"
                          },
                          "Home_Campus_Email": {
                            "type": "string"
                          },
                          "Home_Campus_User_Eppn": {
                            "type": "string"
                          },
                          "Home_Campus_User_Identifier": {
                            "type": "string"
                          },
                          "Host_Campus_Code": {
                            "type": "string"
                          },
                          "Host_Campus_User_Eppn": {
                            "type": "string"
                          },
                          "Host_Campus_User_Identifier": {
                            "type": "string"
                          },
                          "Last_Name": {
                            "type": "string"
                          },
                          "State": {
                            "type": "string"
                          },
                          "ZipCode": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "Address",
                          "Birthdate",
                          "City",
                          "Classification",
                          "First_Name",
                          "Gender",
                          "Home_Campus_Code",
                          "Home_Campus_Email",
                          "Home_Campus_User_Eppn",
                          "Home_Campus_User_Identifier",
                          "Host_Campus_Code",
                          "Host_Campus_User_Eppn",
                          "Host_Campus_User_Identifier",
                          "Last_Name",
                          "State",
                          "ZipCode"
                        ]
                      }
                    }
                  },
                  "required": [
                    "Student_PII"
                  ]
                }
              example: |
                {
                   "Student_PII":[
                      {
                         "Address":"value",
                         "Birthdate":"12-31-1995",
                         "City":"San Fransisco",
                         "Classification":"freshmen",
                         "First_Name":"John",
                         "Gender":"male",
                         "encrypted_SSN": “c5fg2fgwgfk5wgimfg656f56f562526lgg”,
                         "Home_Campus_Code":"UCB",
                         "Home_Campus_Email":"ucb-info@ucop.edu",
                         "Home_Campus_User_Eppn":"value",
                         "Home_Campus_User_Identifier":"value",
                         "Host_Campus_Code":"UCLA",
                         "Host_Campus_User_Eppn":"value",
                         "Host_Campus_User_Identifier":"value",
                         "Last_Name":"Smith",
                         "State":"CA",
                         "ZipCode":"value"
                      }
                   ]
                }
                
            
    
/Grades:
  /IF-grades-1:
    description:
    post:
      description: <<insert text or markdown here>>
      body:
        application/json:
          schema: | 
            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "id": "/",
              "type": "object",
              "properties": {
                "Host_Campus_Code": {
                  "id": "Host_Campus_Code",
                  "type": "string"
                },
                "Home_Campus_Student_Identifier": {
                  "id": "Home_Campus_Student_Identifier",
                  "type": "string"
                },
                "Academic_Term": {
                  "id": "Academic_Term",
                  "type": "string"
                },
                "Academic_Term_Type": {
                  "id": "Academic_Term_Type",
                  "type": "string"
                },
                "Academic_Year": {
                  "id": "Academic_Year",
                  "type": "string"
                },
                "Course_Offering_Code": {
                  "id": "Course_Offering_Code",
                  "type": "string"
                },
                "Course_Title": {
                  "id": "Course_Title",
                  "type": "string"
                },
                "Section_Resource_Number": {
                  "id": "Section_Resource_Number",
                  "type": "string"
                },
                "Grade_Preference": {
                  "id": "Grade_Preference",
                  "type": "string"
                }
              }
            }
          example: |
            {
               "Host_Campus_Code":"UCB",
               "Home_Campus_Student_Identifier":"123456789",
               "Academic_Term":"Fall",
               "Academic_Term_Type":"Quarter",
               "Academic_Year":"2015",
               "Course_Offering_Code":"HIS",
               "Course_Title":"Calculus for Science, Engineering and Mathematics",
               "Section_Resource_Number":"12345",
               "Grade_Preference":"Grade"
            }
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "$schema": "http://json-schema.org/draft-04/schema#",
                  "id": "/",
                  "type": "object",
                  "properties": {
                    "functionality": {
                      "id": "functionality",
                      "type": "string"
                    },
                    "method": {
                      "id": "method",
                      "type": "string"
                    },
                    "verb": {
                      "id": "verb",
                      "type": "string"
                    },
                    "status": {
                      "id": "status",
                      "type": "string"
                    },
                    "confirmationId": {
                      "id": "confirmationId",
                      "type": "string"
                    }
                  }
                }
              example: |
                {
                   "functionality":"Grades",
                   "method":"Grade-Preference-Change-Notification",
                   "verb":"POST",
                   "status":"ACK",
                   "confirmationId":"123ZULU321"
                }
  /IF-grades-2:
    description: Student-Grades-Request
    /{year}:
      /{term}:
          get:
            description: CCES Hub requests Grades for a particular student from the HOST campus.
            queryParameters:
              hostStudentId:
            responses:    
            body:
              application/json:
                schema: |
                  {
                    "$schema": "http://json-schema.org/draft-04/schema#",
                    "id": "/",
                    "type": "object",
                    "properties": {
                      "Host_Campus_Student_Identifier": {
                        "id": "Host_Campus_Student_Identifier",
                        "type": "string"
                      },
                      "Host_Campus_Code": {
                        "id": "Host_Campus_Code",
                        "type": "string"
                      },
                      "Home_Campus_Student_Identifier": {
                        "id": "Home_Campus_Student_Identifier",
                        "type": "string"
                      },
                      "Home_Campus_Code": {
                        "id": "Home_Campus_Code",
                        "type": "string"
                      },
                      "First_Name": {
                        "id": "First_Name",
                        "type": "string"
                      },
                      "Last_Name": {
                        "id": "Last_Name",
                        "type": "string"
                      },
                      "Student_Grades": {
                        "id": "Student_Grades",
                        "type": "array",
                        "items": {
                          "id": "0",
                          "type": "object",
                          "properties": {
                            "Academic_Term": {
                              "id": "Academic_Term",
                              "type": "string"
                            },
                            "Academic_Term_Type": {
                              "id": "Academic_Term_Type",
                              "type": "string"
                            },
                            "Academic_Year": {
                              "id": "Academic_Year",
                              "type": "string"
                            },
                            "Course_Offering_Code": {
                              "id": "Course_Offering_Code",
                              "type": "string"
                            },
                            "Course_Title": {
                              "id": "Course_Title",
                              "type": "string"
                            },
                            "Section_Resource_Number": {
                              "id": "Section_Resource_Number",
                              "type": "string"
                            },
                            "Grade_Preference": {
                              "id": "Grade_Preference",
                              "type": "string"
                            },
                            "Grade": {
                              "id": "Grade",
                              "type": "string"
                            },
                            "Units": {
                              "id": "Units",
                              "type": "string"
                            }
                          }
                        }
                      }
                    }
                  }
                example: | 
                  {
                   "Host_Campus_Student_Identifier":"123456789",
                   "Host_Campus_Code":"UCSB",
                   "Home_Campus_Student_Identifier":"987654321",
                   "Home_Campus_Code":"UCD",
                   "First_Name":"John",
                   "Last_Name":"Smith",
                   "Student_Grades":[
                      {
                         "Academic_Term":"Fall",
                         "Academic_Term_Type":"Quarter",
                         "Academic_Year":"2015",
                         "Course_Offering_Code":"HIST 101",
                         "Course_Title":"Calculus for Science, Engineering and Mathematics",
                         "Section_Resource_Number":"12345",
                         "Grade_Preference":"Grade",
                         "Grade":"TBD",
                         "Units":"credit"
                      }
                   ]
                  }
  /IF-grades-4:
    description: Relay-Student-Grades-to-Host-campus
    post:
      description: CCES Hub relays the Student Grades to the HOME campus.
      body:
        application/json:
          schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "id": "/",
                "type": "object",
                "properties": {
                  "Sender": {
                    "id": "Sender",
                    "type": "string"
                  },
                  "Transaction_Id": {
                    "id": "Transaction_Id",
                    "type": "string"
                  },
                  "Host_Campus_Code": {
                    "id": "Host_Campus_Code",
                    "type": "string"
                  },
                  "Host_Campus_Student_Identifier": {
                    "id": "Host_Campus_Student_Identifier",
                    "type": "string"
                  },
                  "Home_Campus_Student_Identifier": {
                    "id": "Home_Campus_Student_Identifier",
                    "type": "string"
                  },
                  "Academic_Term": {
                    "id": "Academic_Term",
                    "type": "string"
                  },
                  "Academic_Term_Type": {
                    "id": "Academic_Term_Type",
                    "type": "string"
                  },
                  "Academic_Year": {
                    "id": "Academic_Year",
                    "type": "string"
                  },
                  "Course_Offering_Code": {
                    "id": "Course_Offering_Code",
                    "type": "string"
                  },
                  "Course_Title": {
                    "id": "Course_Title",
                    "type": "string"
                  },
                  "Section_Resource_Number": {
                    "id": "Section_Resource_Number",
                    "type": "string"
                  },
                  "First_Name": {
                    "id": "First_Name",
                    "type": "string"
                  },
                  "Last_Name": {
                    "id": "Last_Name",
                    "type": "string"
                  },
                  "Grade": {
                    "id": "Grade",
                    "type": "string"
                  },
                  "Grade_Preference": {
                    "id": "Grade_Preference",
                    "type": "string"
                  },
                  "Units": {
                    "id": "Units",
                    "type": "string"
                  }
                }
              }
          example: | 
              {
                 "Sender":"CCES_HUB",
                 "Transaction_Id":"1122334455",
                 "Host_Campus_Code":"UCB",
                 "Host_Campus_Student_Identifier":"123456789",
                 "Home_Campus_Student_Identifier":"987654321",
                 "Academic_Term":"Fall",
                 "Academic_Term_Type":"Quarter",
                 "Academic_Year":"2015",
                 "Course_Offering_Code":"HIS",
                 "Course_Title":"Calculus for Science, Engineering and Mathematics",
                 "Section_Resource_Number":"TBD",
                 "First_Name":"John",
                 "Last_Name":"Smith",
                 "Grade":"TBD",
                 "Grade_Preference":"Grade",
                 "Units":"credit"
              }
      responses:  
        200:
          body:
            application/json:
              schema: |
                {
                  "$schema": "http://json-schema.org/draft-04/schema#",
                  "id": "/",
                  "type": "object",
                  "properties": {
                    "status": {
                      "id": "status",
                      "type": "string"
                    }
                  }
                }
              example: |
                {
                   "status":"ACK"
                }